# Remove "Are you sure?" message
confirm_os_window_close 0
# Remove squirt sound
enable_audio_bell no

# Unbind panes and other functionality.
map ctrl+shift+escape no_op
map ctrl+shift+t no_op
map ctrl+shift+r no_op
map kitty_mod+f2 no_op
map kitty_mod+l no_op

# Scroll up/down by full page
map shift+page_up   scroll_page_up
map shift+page_down scroll_page_down

# Font zoom shortcuts
map ctrl+plus change_font_size all +0.5
map ctrl+minus change_font_size all -0.5
map ctrl+0 change_font_size all 16.0

# =========================
# Font
# =========================
#font_family      CaskaydiaCove NF
#bold_font        CaskaydiaCove NF
#italic_font      CaskaydiaCove NF
#bold_italic_font CaskaydiaCove NF
#font_size        16.0

# =========================
# Window
# =========================
background_opacity 0.80

# =========================
# Shell
# =========================
#shell /usr/bin/zsh

# =========================
# Colors
# =========================
background #2E3440
# Optional foreground (Kitty defaults to color7 if omitted)
foreground #D8DEE9

# Normal colors
color0  #3B4252
color1  #BF616A
color2  #A3BE8C
color3  #EBCB8B
color4  #81A1C1
color5  #B48EAD
color6  #88C0D0
color7  #E5E9F0

# Bright colors
color8  #4C566A
color9  #BF616A
color10 #A3BE8C
color11 #EBCB8B
color12 #81A1C1
color13 #B48EAD
color14 #8FBCBB
color15 #ECEFF4
