[bar]
  [bar.default]
    [bar.default.monitor]
      [bar.default.monitor.DP-3]
        center = ["media2"]
        start = ["control-center", "wallpaper", "workspaces", "focus-column-left", "focus-column-right", "active_window2"]

[calendar]
  enabled = true
  [calendar.account]
    [calendar.account.personal_google]
      color = "primary"
      name = "Personlig kalender"
      type = "google"

[control_center]
  hidden_tabs = ["monitor", "power", "network"]
  [control_center.calendar]
    show_week_numbers = true

[lockscreen]
  lock_before_suspend = false

[lockscreen_widgets]
  widget_order = ["lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@DP-3", "lockscreen-login-box@DP-2"]
  [lockscreen_widgets.widget]
    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
      box_height = 196.0
      box_width = 810.0
      cx = 960.0
      cy = 898.0
      output = "DP-2"
      placement_height = 1080.0
      placement_width = 1920.0
      rotation = 0.0
      type = "login_box"
      [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = false
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true
    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
      box_height = 196.0
      box_width = 810.0
      cx = 540.0
      cy = 1596.4444580078125
      output = "DP-3"
      placement_height = 1920.0
      placement_width = 1080.0
      rotation = 0.0
      type = "login_box"
      [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = false
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true
    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
      box_height = 196.0
      box_width = 810.0
      cx = 640.0
      cy = 659.3333740234375
      output = "HDMI-A-1"
      placement_height = 720.0
      placement_width = 1280.0
      rotation = 0.0
      type = "login_box"
      [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = false
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[wallpaper]
  [wallpaper.default]
    path = "/home/jw/Pictures/Wallpapers/wallhaven/wallhaven-4ywjjk.jpg"
  [wallpaper.last]
    path = "/home/jw/Pictures/Wallpapers/wallhaven/wallhaven-4ywjjk.jpg"
  [wallpaper.monitors]
    [wallpaper.monitors.DP-2]
      path = "/home/jw/Pictures/Wallpapers/wallhaven/wallhaven-4ywjjk.jpg"
    [wallpaper.monitors.DP-3]
      path = "/home/jw/Pictures/Wallpapers/wallhaven/wallhaven-6lyg5q.jpg"

[widget]
  [widget.bluetooth]
    enabled = false
