# A TOML linter such as Tombi can use this schema to validate your config.
# If you encounter any problems, please file an issue at https://github.com/yazi-rs/schemas.

#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]


# DISABLED KEYMAPS
[[mgr.prepend_keymap]]
on = [ "g", "h" ]
run = "noop"
[[mgr.prepend_keymap]]
on = [ "g", "d" ]
run = "noop"

[[mgr.prepend_keymap]]
on = [ "g", "t" ]
run = "noop"

[[mgr.prepend_keymap]]
on = [ "g", "<Space>" ]
run = "noop"


# USER KEYMAPS
[[mgr.prepend_keymap]]
on = [ "g", "F" ]
run = "follow"
desc = "Follow hovered symlink"

[[mgr.prepend_keymap]]
on = "e"
run = "cd --interactive"
desc = "Jump interactively"

[[mgr.prepend_keymap]]
on = [ "m", "c" ]
run = "linemode size_and_mtime"
desc = "Linemode: size & mtime"

[[mgr.prepend_keymap]]
on = "'"
run = "plugin fzf"
desc = "Jump to a file/directory via fzf"

[[mgr.prepend_keymap]]
on = "H"
run = "leave"
desc = "Back to the parent directory"

[[mgr.prepend_keymap]]
on = "L"
run = "enter"
desc = "Enter the child directory"

#[[mgr.prepend_keymap]]
#on = [ "g", "G" ]
#run = "arrow bot"
#desc = "Go to bottom"

[[mgr.prepend_keymap]]
on = "<S-Up>"
run = "arrow prev"
desc = "Previous file"
[[mgr.prepend_keymap]]
on = "<S-Down>"
run = "arrow next"
desc = "Next file"

[[mgr.prepend_keymap]]
on = "<C-o>"
run = "back"
desc = "Back to previous directory" 

[[mgr.prepend_keymap]]
on = "<C-i>"
run = "forward"
desc = "Forward to next directory" 

[[mgr.prepend_keymap]]
on   = "="
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on   = "<C-Enter>"
run  = "shell --orphan --confirm 'nautilus .'"
desc = "Open the current directory in Nautilus"

[[mgr.prepend_keymap]]
on   = [ "g", "P" ]
run  = "shell -- wl-paste > pasted-image.png"
desc = "Paste image from clipboard"


# PLUGIN KEYMAPS
# Smart-filter
[[mgr.prepend_keymap]]
on = [ "g", "f" ]
run = "plugin smart-filter"
desc = "Filter traversal"

# Confirm-quit
[[mgr.prepend_keymap]]
on   = "q"
run  = "plugin confirm-quit"
desc = "Confirm quit for tabs"

# Relative-motions
[[mgr.prepend_keymap]]
on = "!"
run = "plugin relative-motions 1"
desc = "Move in relative steps"
[[mgr.prepend_keymap]]
on = '"'
run = "plugin relative-motions 2"
desc = "Move in relative steps"
[[mgr.prepend_keymap]]
on = "#"
run = "plugin relative-motions 3"
desc = "Move in relative steps"
[[mgr.prepend_keymap]]
on = "¤"
run = "plugin relative-motions 4"
desc = "Move in relative steps"
[[mgr.prepend_keymap]]
on = "%"
run = "plugin relative-motions 5"
desc = "Move in relative steps"
[[mgr.prepend_keymap]]
on = "&"
run = "plugin relative-motions 6"
desc = "Move in relative steps"
[[mgr.prepend_keymap]]
on = "/"
run = "plugin relative-motions 7"
desc = "Move in relative steps"
[[mgr.prepend_keymap]]
on = "("
run = "plugin relative-motions 8"
desc = "Move in relative steps"
[[mgr.prepend_keymap]]
on = ")"
run = "plugin relative-motions 9"
desc = "Move in relative steps"

# Toggle-pane
[[mgr.prepend_keymap]]
on   = "<C-e>"
run  = "plugin toggle-pane min-parent"
desc = "Show or hide the parent pane"
[[mgr.prepend_keymap]]
on   = "E"
run  = "plugin toggle-pane max-parent"
desc = "Maximize or restore the parent pane"
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-current"
desc = "Maximize or restore the current pane"
[[mgr.prepend_keymap]]
on   = "<C-t>"
run  = "plugin toggle-pane min-current"
desc = "Show or hide the current pane"
[[mgr.prepend_keymap]]
on   = "<C-p>"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"
[[mgr.prepend_keymap]]
on   = "P"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
[[mgr.prepend_keymap]]
on   = "W"
run  = "plugin toggle-pane reset"
desc = "Reset ratio"

# Jump-to-char
[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin jump-to-char"
desc = "Jump to char"

# whoosh hop
[[mgr.prepend_keymap]]
on = "z"
run = "plugin whoosh jump_by_key"
desc = "Jump bookmark by key"
# Direct fuzzy search access
[[mgr.prepend_keymap]]
on = ">"
run = "plugin whoosh jump_by_fzf"
desc = "Direct fuzzy search for bookmarks"
# Basic bookmark operations
[[mgr.prepend_keymap]]
on = [ "Z", "a" ]
run = "plugin whoosh save"
desc = "Add bookmark (hovered file/directory)"
[[mgr.prepend_keymap]]
on = [ "Z", "A" ]
run = "plugin whoosh save_cwd"
desc = "Add bookmark (current directory)"
# Temporary bookmarks
[[mgr.prepend_keymap]]
on = [ "Z", "t" ]
run = "plugin whoosh save_temp"
desc = "Add temporary bookmark (hovered file/directory)"
[[mgr.prepend_keymap]]
on = [ "Z", "T" ]
run = "plugin whoosh save_cwd_temp"
desc = "Add temporary bookmark (current directory)"
# TODO
# Jump to bookmarks
# Important directories
[[mgr.prepend_keymap]]
on = "<A-h>"
run = "plugin whoosh jump_key_h"
desc = "Jump directly to bookmark with key h"
[[mgr.prepend_keymap]]
on = "<A-r>"
run = "plugin whoosh jump_key_r"
desc = "Jump directly to bookmark with key r"
[[mgr.prepend_keymap]]
on = "<A-d>"
run = "plugin whoosh jump_key_d"
desc = "Jump directly to bookmark with key d"
[[mgr.prepend_keymap]]
on = "<A-p>"
run = "plugin whoosh jump_key_p"
desc = "Jump directly to bookmark with key p"
[[mgr.prepend_keymap]]
on = "<A-v>"
run = "plugin whoosh jump_key_v"
desc = "Jump directly to bookmark with key v"
[[mgr.prepend_keymap]]
on = "<A-m>"
run = "plugin whoosh jump_key_m"
desc = "Jump directly to bookmark with key m"
[[mgr.prepend_keymap]]
on = "<A-c>"
run = "plugin whoosh jump_key_c"
desc = "Jump directly to bookmark with key c"
[[mgr.prepend_keymap]]
on = "<A-y>"
run = "plugin whoosh jump_key_y"
desc = "Jump directly to bookmark with key y"
[[mgr.prepend_keymap]]
on = "<A-n>"
run = "plugin whoosh jump_key_n"
desc = "Jump directly to bookmark with key n"
[[mgr.prepend_keymap]]
on = "<A-l>"
run = "plugin whoosh jump_key_l"
desc = "Jump directly to bookmark with key l"
[[mgr.prepend_keymap]]
on = "<A-t>"
run = "plugin whoosh jump_key_t"
desc = "Jump directly to bookmark with key t"
[[mgr.prepend_keymap]]
on = "<A-u>"
run = "plugin whoosh jump_key_u"
desc = "Jump directly to bookmark with key u"
[[mgr.prepend_keymap]]
on = "<A-o>"
run = "plugin whoosh jump_key_o"
desc = "Jump directly to bookmark with key o"
[[mgr.prepend_keymap]]
on = "<A-e>"
run = "plugin whoosh jump_key_e"
desc = "Jump directly to bookmark with key e"
[[mgr.prepend_keymap]]
on = "<A-s>"
run = "plugin whoosh jump_key_s"
desc = "Jump directly to bookmark with key s"
[[mgr.prepend_keymap]]
on = [ "Z", "f" ]
run = "plugin whoosh jump_by_fzf"
desc = "Jump bookmark by fzf"
# Delete bookmarks
[[mgr.prepend_keymap]]
on = [ "Z", "d" ]
run = "plugin whoosh delete_by_key"
desc = "Delete bookmark by key"
[[mgr.prepend_keymap]]
on = [ "Z", "D" ]
run = "plugin whoosh delete_by_fzf"
desc = "Delete bookmarks by fzf (use TAB to select multiple)"
[[mgr.prepend_keymap]]
on = [ "Z", "C" ]
run = "plugin whoosh delete_all"
desc = "Delete all user bookmarks"
# Rename bookmarks
[[mgr.prepend_keymap]]
on = [ "Z", "r" ]
run = "plugin whoosh rename_by_key"
desc = "Rename bookmark by key"
[[mgr.prepend_keymap]]
on = [ "Z", "R" ]
run = "plugin whoosh rename_by_fzf"
desc = "Rename bookmark by fzf"

# mount
[[mgr.prepend_keymap]]
on  = [ "M", "m" ]
run = "plugin mount"

# Sudo
[[mgr.prepend_keymap]]
on = [ "R", "p", "p" ]
run = "plugin sudo -- paste"
desc = "sudo paste"
[[mgr.prepend_keymap]]
on = [ "R", "P" ]
run = "plugin sudo -- paste --force"
desc = "sudo paste"
[[mgr.prepend_keymap]]
on = [ "R", "o" ]
run = "plugin sudo -- open"
desc = "sudo open editor"
[[mgr.prepend_keymap]]
on = [ "R", "r" ]
run = "plugin sudo -- rename"
desc = "sudo rename"
[[mgr.prepend_keymap]]
on = [ "R", "p", "l" ]
run = "plugin sudo -- link"
desc = "sudo link"
[[mgr.prepend_keymap]]
on = [ "R", "p", "r" ]
run = "plugin sudo -- link --relative"
desc = "sudo link relative path"
[[mgr.prepend_keymap]]
on = [ "R", "p", "L" ]
run = "plugin sudo -- hardlink"
desc = "sudo hardlink"
[[mgr.prepend_keymap]]
on = [ "R", "a" ]
run = "plugin sudo -- create"
desc = "sudo create"
[[mgr.prepend_keymap]]
on = [ "R", "D" ]
run = "plugin sudo -- remove --permanently"
desc = "sudo delete"
[[mgr.prepend_keymap]]
on = [ "R", "c" ]
run = "plugin sudo -- chmod"
desc = "sudo chmod"

# diff
[[mgr.prepend_keymap]]
on = [ "i", "d" ]
run  = "plugin diff"
desc = "Diff the selected with the hovered file"

# augment-command
[[mgr.prepend_keymap]]
on = "h"
run = "plugin augment-command.leave"
desc = "Go back to the parent directory"
[[mgr.prepend_keymap]]
on = "l"
run = "plugin augment-command.enter"
desc = "Enter the child directory, or open the file"
[[mgr.prepend_keymap]]
on = [ "<C-j>" ]
run = [ "leave", "arrow 1", "enter" ]
desc = "Move the cursor down in the parent directory"
[[mgr.prepend_keymap]]
on = [ "<C-k>" ]
run = [ "leave", "arrow -1", "enter" ]
desc = "Move the cursor up in the parent directory"
[[mgr.prepend_keymap]]
on = "<Down>"
run = "plugin augment-command.arrow -- 15"
desc = "Move cursor down"
[[mgr.prepend_keymap]]
on = "<Up>"
run = "plugin augment-command.arrow -- -15"
desc = "Move cursor up"
[[mgr.prepend_keymap]]
on = "o"
run = "plugin augment-command.shell -- '$EDITOR %s' --block --exit-if-dir"
desc = "Open files with the default editor"
[[mgr.prepend_keymap]]
on = "r"
run = "plugin augment-command.rename -- --cursor=before_ext"
desc = "Rename a file or directory"
[[mgr.prepend_keymap]]
on = "d"
run = "plugin augment-command.remove"
desc = "Move the files to the trash"
[[mgr.prepend_keymap]]
on = "D"
run = "plugin augment-command.remove -- --permanently"
desc = "Permanently delete the files"
[[mgr.prepend_keymap]]
on = "+"
run = "plugin augment-command.create"
desc = "Add files to an archive"

# Chmod
[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

# convert
[[mgr.prepend_keymap]]
on = [ "b", "p" ]
run = "plugin convert -- --extension='png'"
desc = "Convert to PNG"
[[mgr.prepend_keymap]]
on = [ "b", "j" ]
run = "plugin convert -- --extension='jpg'"
desc = "Convert to JPG"
[[mgr.prepend_keymap]]
on = [ "b", "w" ]
run = "plugin convert -- --extension='webp'"
desc = "Convert to WebP"

# pref-by-location
[[mgr.prepend_keymap]]
# Toggle Hidden
on = "."
run = [ "hidden toggle", "plugin pref-by-location -- save" ]
desc = "Toggle the visibility of hidden files"
[[mgr.prepend_keymap]]
# Linemode
on = [ "m", "s" ]
run = [ "linemode size", "plugin pref-by-location -- save" ]
desc = "Linemode: size"
[[mgr.prepend_keymap]]
on = [ "m", "c" ]
run = [ "linemode size_and_mtime", "plugin pref-by-location -- save" ]
desc = "Linemode: size & mtime"
[[mgr.prepend_keymap]]
on = [ "m", "p" ]
run = [ "linemode permissions", "plugin pref-by-location -- save" ]
desc = "Linemode: permissions"
[[mgr.prepend_keymap]]
on = [ "m", "b" ]
run = [ "linemode btime", "plugin pref-by-location -- save" ]
desc = "Linemode: btime"
[[mgr.prepend_keymap]]
on = [ "m", "m" ]
run = [ "linemode mtime", "plugin pref-by-location -- save" ]
desc = "Linemode: mtime"
[[mgr.prepend_keymap]]
on = [ "m", "o" ]
run = [ "linemode owner", "plugin pref-by-location -- save" ]
desc = "Linemode: owner"
[[mgr.prepend_keymap]]
on = [ "m", "n" ]
run = [ "linemode none", "plugin pref-by-location -- save" ]
desc = "Linemode: none"
[[mgr.prepend_keymap]]
# Any changes during disabled state won't be saved to save file.
on = [ ",", "t" ]
run = "plugin pref-by-location -- toggle"
desc = "Toggle auto-save preferences"
[[mgr.prepend_keymap]]
on = [ ",", "d" ]
run = "plugin pref-by-location -- disable"
desc = "Disable auto-save preferences"
[[mgr.prepend_keymap]]
# This will reset any preference changes for the current working directory (CWD)
# then fall back to the predefined preferences in init.lua or yazi.toml.
on = [ ",", "R" ]
run = "plugin pref-by-location -- reset"
desc = "Reset preference of cwd"
[[mgr.prepend_keymap]]
on = [ ",", "m" ]
run = [ "sort mtime --reverse=no", "linemode mtime", "plugin pref-by-location -- save" ]
desc = "Sort by modified time"
[[mgr.prepend_keymap]]
on = [ ",", "M" ]
run = [ "sort mtime --reverse", "linemode mtime", "plugin pref-by-location -- save" ]
desc = "Sort by modified time (reverse)"
[[mgr.prepend_keymap]]
on = [ ",", "b" ]
run = [ "sort btime --reverse=no", "linemode btime", "plugin pref-by-location -- save" ]
desc = "Sort by birth time"
[[mgr.prepend_keymap]]
on = [ ",", "B" ]
run = [ "sort btime --reverse", "linemode btime", "plugin pref-by-location -- save" ]
desc = "Sort by birth time (reverse)"
[[mgr.prepend_keymap]]
on = [ ",", "e" ]
run = [ "sort extension --reverse=no", "plugin pref-by-location -- save" ]
desc = "Sort by extension"
[[mgr.prepend_keymap]]
on = [ ",", "E" ]
run = [ "sort extension --reverse", "plugin pref-by-location -- save" ]
desc = "Sort by extension (reverse)"
[[mgr.prepend_keymap]]
on = [ ",", "a" ]
run = [ "sort alphabetical --reverse=no", "plugin pref-by-location -- save" ]
desc = "Sort alphabetically"
[[mgr.prepend_keymap]]
on = [ ",", "A" ]
run = [ "sort alphabetical --reverse", "plugin pref-by-location -- save" ]
desc = "Sort alphabetically (reverse)"
[[mgr.prepend_keymap]]
on = [ ",", "n" ]
run = [ "sort natural --reverse=no", "plugin pref-by-location -- save" ]
desc = "Sort naturally"
[[mgr.prepend_keymap]]
on = [ ",", "N" ]
run = [ "sort natural --reverse", "plugin pref-by-location -- save" ]
desc = "Sort naturally (reverse)"
[[mgr.prepend_keymap]]
on = [ ",", "s" ]
run = [ "sort size --reverse=no", "linemode size", "plugin pref-by-location -- save" ]
desc = "Sort by size"
[[mgr.prepend_keymap]]
on = [ ",", "S" ]
run = [ "sort size --reverse", "linemode size", "plugin pref-by-location -- save" ]
desc = "Sort by size (reverse)"
[[mgr.prepend_keymap]]
on = [ ",", "c" ]
run = [ "sort size --reverse=no", "linemode size_and_mtime", "plugin pref-by-location -- save" ]
desc = "Sort by size & mtime"
[[mgr.prepend_keymap]]
on = [ ",", "C" ]
run = [ "sort size --reverse", "linemode size_and_mtime", "plugin pref-by-location -- save" ]
desc = "Sort by size & mtime"
[[mgr.prepend_keymap]]
on = [ ",", "r" ]
run = [ "sort random --reverse=no", "plugin pref-by-location -- save" ]
desc = "Sort randomly"

# System-clipboard
[[mgr.prepend_keymap]]
on = "<C-y>"
run = "plugin system-clipboard"

# zoom
[[mgr.prepend_keymap]]
on   = "å"
run  = "plugin zoom 1"
desc = "Zoom in hovered file"
[[mgr.prepend_keymap]]
on   = "æ"
run  = "plugin zoom -1"
desc = "Zoom out hovered file"

# fuzzy grep
[[mgr.prepend_keymap]]
on  = [ "*" ]
run = "plugin yafg"

# custom shell
[[mgr.prepend_keymap]]
on = [ ":" ]
run = 'plugin custom-shell -- auto --interactive'
desc = "custom-shell as default"

# gvfs mount
[[mgr.prepend_keymap]]
on = [ "M", "M" ]
run = "plugin gvfs -- select-then-mount --jump"
desc = "Select device to mount and jump to its mount point"

[[mgr.prepend_keymap]]
on = [ "M", "r" ]
run = "plugin gvfs -- remount-current-cwd-device"
desc = "Remount device under cwd"

[[mgr.prepend_keymap]]
on = [ "M", "U" ]
run = "plugin gvfs -- select-then-unmount --eject"
desc = "Select device then eject"

[[mgr.prepend_keymap]]
on = [ "M", "a" ]
run = "plugin gvfs -- add-mount"
desc = "Add a GVFS mount URI"

[[mgr.prepend_keymap]]
on = [ "M", "e" ]
run = "plugin gvfs -- edit-mount"
desc = "Edit a GVFS mount URI"

[[mgr.prepend_keymap]]
on = [ "M", "R" ]
run = "plugin gvfs -- remove-mount"
desc = "Remove a GVFS mount URI"

[[mgr.prepend_keymap]]
on = [ "g", "m" ]
run = "plugin gvfs -- jump-to-device --automount"
desc = "Automount then select device to jump to its mount point"

# open-paths
[[mgr.prepend_keymap]]
on = [ "g", "o" ]
run = "plugin open-paths"
desc = "Jump to a path open in another Yazi"

[[mgr.prepend_keymap]]
on = [ "g", "p" ]
run = "plugin open-paths -- copy"
desc = "Copy a path open in another Yazi"
